sonar.projectKey=alfonsomartin03_Second-Serve
sonar.organization=alfonsomartin03-second-serve

sonar.sources=.
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/coverage/**
sonar.sourceEncoding=UTF-8
