sonar.organization=alfonsomartin03
sonar.projectKey=alfonsomartin03_Second-Serve

# Source paths to scan
sonar.sources=.

# Exclude dependencies and build outputs
sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/coverage/**

# Source encoding
sonar.sourceEncoding=UTF-8
